FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_YOLO_MODEL_URL=/models/yolo/yolo11n.onnx
ARG NEXT_PUBLIC_YOLO_LABELS_URL=/models/yolo/coco.names
ARG NEXT_PUBLIC_LLM_RUNTIME=transformers
ARG NEXT_PUBLIC_LLM_DEVICE=webgpu
ARG NEXT_PUBLIC_LLM_MODEL_ID=gemma-4-E2B-it-ONNX
ARG NEXT_PUBLIC_LLM_MODEL_URL=/models/gemma4-e2b-it-onnx
ARG NEXT_PUBLIC_LANE_MODEL_URL=/models/lane/segformer-b0-cityscapes/model_quantized.onnx
ARG NEXT_PUBLIC_LANE_MODEL_INPUT_SIZE=224
ARG NEXT_PUBLIC_LANE_MODEL_PROVIDER=webgpu,wasm
ARG NEXT_PUBLIC_LANE_MODEL_TARGET_CHANNEL=0
ARG NEXT_PUBLIC_LANE_MODEL_THRESHOLD=0.5
ARG NEXT_PUBLIC_STREAM_GATEWAY_URL=http://localhost:3010

ENV NEXT_PUBLIC_YOLO_MODEL_URL=$NEXT_PUBLIC_YOLO_MODEL_URL
ENV NEXT_PUBLIC_YOLO_LABELS_URL=$NEXT_PUBLIC_YOLO_LABELS_URL
ENV NEXT_PUBLIC_LLM_RUNTIME=$NEXT_PUBLIC_LLM_RUNTIME
ENV NEXT_PUBLIC_LLM_DEVICE=$NEXT_PUBLIC_LLM_DEVICE
ENV NEXT_PUBLIC_LLM_MODEL_ID=$NEXT_PUBLIC_LLM_MODEL_ID
ENV NEXT_PUBLIC_LLM_MODEL_URL=$NEXT_PUBLIC_LLM_MODEL_URL
ENV NEXT_PUBLIC_LANE_MODEL_URL=$NEXT_PUBLIC_LANE_MODEL_URL
ENV NEXT_PUBLIC_LANE_MODEL_INPUT_SIZE=$NEXT_PUBLIC_LANE_MODEL_INPUT_SIZE
ENV NEXT_PUBLIC_LANE_MODEL_PROVIDER=$NEXT_PUBLIC_LANE_MODEL_PROVIDER
ENV NEXT_PUBLIC_LANE_MODEL_TARGET_CHANNEL=$NEXT_PUBLIC_LANE_MODEL_TARGET_CHANNEL
ENV NEXT_PUBLIC_LANE_MODEL_THRESHOLD=$NEXT_PUBLIC_LANE_MODEL_THRESHOLD
ENV NEXT_PUBLIC_STREAM_GATEWAY_URL=$NEXT_PUBLIC_STREAM_GATEWAY_URL

RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000

CMD ["node", "server.js"]
